repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
#      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [-m]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo:  https://github.com/milin/giticket
    rev: v1.3
    hooks:
      - id:  giticket
        args: ['--mode=regex_match', '--regex=([a-zA-Z]{3,4}-[0-9]*)', '--format={ticket} {commit_msg}']
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.1 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        name: pycln app
        args: [--config=pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args: [--config, .flake8]
#  - repo: https://github.com/pycqa/pylint
#    rev: v2.11.1
#    hooks:
#      - id: pylint
#        # Disable docstring checks - this is intended to be temporary
#        args: [-j, "0", --rcfile=.pylintrc]
#        exclude: "app/alembic"
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [-c, .bandit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        name: mypy api
        files: ^app/
        additional_dependencies: [types-pytz, types-requests, types-jwt]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort app
        files: ^app/
        args: ["--profile", "black"]
