name: PR to develop or main

on:
  pull_request:
    branches: [main, develop]

env:
  IMAGE_REGISTRY: us.scr.io

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ~3.10.5
      - uses: pre-commit/action@v3.0.0

  push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      uses: raccoondev/push-docker-gcr
      with:
        gcr_host: gcr.io
        image_name: message-relay
        image_tag: latest
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
